import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { gzipSync } from "node:zlib"
import { dirname, join, relative, sep } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import esbuild from "esbuild"
import { sassPlugin } from "esbuild-sass-plugin"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..", "..")
const srcDir = join(here, "src")
const generatedDir = join(here, "generated")
const manifestPath = join(here, "manifest.json")
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"))
const pluginDir = join(repoRoot, "Vault", ".obsidian", "plugins", manifest.id)
const banner = "GENERATED by custom/mermaid-flow/build.mjs — do not edit. Edit src/ and rebuild."

const toRepoPath = (path) => relative(repoRoot, path).split(sep).join("/")

const browserOptions = {
  entryPoints: [join(srcDir, "entries", "browser.ts")],
  bundle: true,
  outfile: join(generatedDir, "engine.js"),
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  charset: "utf8",
  legalComments: "none",
  minify: true,
  banner: { js: `// ${banner}` },
}

const quartzStylesOptions = {
  entryPoints: [join(srcDir, "styles", "hosts", "quartz.scss")],
  bundle: true,
  outfile: join(generatedDir, "engine.css"),
  plugins: [sassPlugin()],
  charset: "utf8",
  legalComments: "none",
  minify: true,
  banner: { css: `/* ${banner} */` },
}

const obsidianOptions = {
  entryPoints: [join(srcDir, "entries", "obsidian.cts")],
  bundle: true,
  outfile: join(pluginDir, "main.js"),
  format: "cjs",
  platform: "browser",
  target: ["es2020"],
  external: ["obsidian"],
  charset: "utf8",
  legalComments: "none",
  banner: { js: `// ${banner}` },
}

const obsidianStylesOptions = {
  entryPoints: [join(srcDir, "styles", "hosts", "obsidian.scss")],
  bundle: true,
  outfile: join(pluginDir, "styles.css"),
  plugins: [sassPlugin()],
  charset: "utf8",
  legalComments: "none",
  banner: { css: `/* ${banner} */` },
}

const outputContent = (result, outputPath) => {
  const output = result.outputFiles?.find((file) => file.path === outputPath)
  if (!output)
    throw new Error(`mermaid-flow build: esbuild did not produce ${toRepoPath(outputPath)}`)
  return output.text
}

export const expectedArtifacts = async () => {
  const manifestSource = readFileSync(manifestPath, "utf8")
  const [browser, quartzStyles, obsidian, obsidianStyles] = await Promise.all([
    esbuild.build({ ...browserOptions, write: false }),
    esbuild.build({ ...quartzStylesOptions, write: false }),
    esbuild.build({ ...obsidianOptions, write: false }),
    esbuild.build({ ...obsidianStylesOptions, write: false }),
  ])

  return {
    manifestId: manifest.id,
    files: [
      { path: browserOptions.outfile, content: outputContent(browser, browserOptions.outfile) },
      {
        path: quartzStylesOptions.outfile,
        content: outputContent(quartzStyles, quartzStylesOptions.outfile),
      },
      { path: obsidianOptions.outfile, content: outputContent(obsidian, obsidianOptions.outfile) },
      {
        path: obsidianStylesOptions.outfile,
        content: outputContent(obsidianStyles, obsidianStylesOptions.outfile),
      },
      { path: join(pluginDir, "manifest.json"), content: manifestSource },
      { path: join(pluginDir, ".hotreload"), content: "" },
    ],
  }
}

export const verifyArtifacts = async () => {
  const expected = await expectedArtifacts()
  const stale = expected.files
    .filter(({ path, content }) => !existsSync(path) || readFileSync(path, "utf8") !== content)
    .map(({ path }) => toRepoPath(path))
  if (stale.length) {
    throw new Error(
      `mermaid-flow check: generated artifacts are stale: ${stale.join(", ")}. Run npm run mermaid-flow:build.`,
    )
  }
  return summarize(expected)
}

export const buildMermaidFlow = async () => {
  const expected = await expectedArtifacts()
  for (const { path, content } of expected.files) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
  }
  return summarize(expected)
}

const summarize = (expected) => {
  const engine = expected.files.filter(({ path }) => path.startsWith(generatedDir))
  return {
    manifestId: expected.manifestId,
    artifacts: expected.files.length,
    engineBytes: Object.fromEntries(
      engine.map(({ path, content }) => [
        toRepoPath(path),
        { minified: Buffer.byteLength(content), gzip: gzipSync(content).byteLength },
      ]),
    ),
  }
}

const formatSizes = (engineBytes) =>
  Object.entries(engineBytes)
    .map(([path, size]) => `${path} ${size.minified} B minified/${size.gzip} B gzip`)
    .join(", ")

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv.includes("--check")) {
    const { manifestId, artifacts, engineBytes } = await verifyArtifacts()
    console.log(
      `mermaid-flow: ${artifacts} generated artifacts are current (${manifestId}); ${formatSizes(engineBytes)}`,
    )
  } else {
    const { manifestId, artifacts, engineBytes } = await buildMermaidFlow()
    console.log(
      `mermaid-flow: built ${artifacts} artifacts for Quartz and Obsidian (${manifestId}); ${formatSizes(engineBytes)}`,
    )
  }
}
