import {
  executionTreeFamily,
  parseBranchAndBoundConfig,
  type ExecutionTreeConfig,
  type ExecutionTreeFrame,
  type ExecutionTreeNode,
  type ExecutionTreeOperations,
} from "../families/execution-tree"
import type { ExecutionTreeRecorder } from "../recorders"
import type { FamilyAlgorithmDefinition } from "../types"

export const branchAndBound = {
  id: "branch-and-bound",
  kind: "rectree",
  family: executionTreeFamily,
  meta: { label: "Branch and Bound" },
  parse: parseBranchAndBoundConfig,
  run(input, ops) {
    const nodes: ExecutionTreeNode[] = [
      {
        id: "root",
        label: "start",
        detail: "0/7 · 0 · bound 116",
        values: [],
        x: 636,
        y: 28,
        depth: 0,
        weight: 0,
        value: 0,
        bound: 116,
      },
      {
        id: "a+",
        label: "take A",
        detail: "2/7 · 40 · bound 116",
        values: [],
        x: 352,
        y: 100,
        depth: 1,
        weight: 2,
        value: 40,
        bound: 116,
      },
      {
        id: "a-",
        label: "skip A",
        detail: "0/7 · 0 · bound 102",
        values: [],
        x: 920,
        y: 100,
        depth: 1,
        weight: 0,
        value: 0,
        bound: 102,
      },
      {
        id: "ab+",
        label: "take B",
        detail: "5/7 · 90 · bound 116",
        values: [],
        x: 139,
        y: 172,
        depth: 2,
        weight: 5,
        value: 90,
        bound: 116,
      },
      {
        id: "ab-",
        label: "skip B",
        detail: "2/7 · 40 · bound 105",
        values: [],
        x: 565,
        y: 172,
        depth: 2,
        weight: 2,
        value: 40,
        bound: 105,
      },
      {
        id: "abc+",
        label: "take C",
        detail: "10/7 · 155 · infeasible",
        values: [],
        x: 68,
        y: 244,
        depth: 3,
        weight: 10,
        value: 155,
        bound: null,
      },
      {
        id: "abc-",
        label: "skip C",
        detail: "5/7 · 90 · bound 107.5",
        values: [],
        x: 210,
        y: 244,
        depth: 3,
        weight: 5,
        value: 90,
        bound: 107.5,
      },
      {
        id: "ac+",
        label: "take C",
        detail: "7/7 · 105 · bound 105",
        values: [],
        x: 423,
        y: 244,
        depth: 3,
        weight: 7,
        value: 105,
        bound: 105,
      },
      {
        id: "ac-",
        label: "skip C",
        detail: "2/7 · 40 · bound 75",
        values: [],
        x: 707,
        y: 244,
        depth: 3,
        weight: 2,
        value: 40,
        bound: 75,
      },
      {
        id: "abcd+",
        label: "take D",
        detail: "9/7 · 125 · infeasible",
        values: [],
        x: 68,
        y: 316,
        depth: 4,
        weight: 9,
        value: 125,
        bound: null,
      },
      {
        id: "abcd-",
        label: "skip D",
        detail: "5/7 · 90 · bound 90",
        values: [],
        x: 210,
        y: 316,
        depth: 4,
        weight: 5,
        value: 90,
        bound: 90,
      },
      {
        id: "acd+",
        label: "take D",
        detail: "11/7 · 140 · infeasible",
        values: [],
        x: 352,
        y: 316,
        depth: 4,
        weight: 11,
        value: 140,
        bound: null,
      },
      {
        id: "acd-",
        label: "skip D",
        detail: "7/7 · 105 · bound 105",
        values: [],
        x: 494,
        y: 316,
        depth: 4,
        weight: 7,
        value: 105,
        bound: 105,
      },
      {
        id: "ac-d+",
        label: "take D",
        detail: "6/7 · 75 · bound 75",
        values: [],
        x: 636,
        y: 316,
        depth: 4,
        weight: 6,
        value: 75,
        bound: 75,
      },
      {
        id: "ac-d-",
        label: "skip D",
        detail: "2/7 · 40 · bound 40",
        values: [],
        x: 778,
        y: 316,
        depth: 4,
        weight: 2,
        value: 40,
        bound: 40,
      },
      {
        id: "a-b+",
        label: "take B",
        detail: "3/7 · 50 · bound 102",
        values: [],
        x: 849,
        y: 172,
        depth: 2,
        weight: 3,
        value: 50,
        bound: 102,
      },
      {
        id: "a-b-",
        label: "skip B",
        detail: "0/7 · 0 · bound 82.5",
        values: [],
        x: 991,
        y: 172,
        depth: 2,
        weight: 0,
        value: 0,
        bound: 82.5,
      },
    ]
    const edges = [
      { from: "root", to: "a+" },
      { from: "root", to: "a-" },
      { from: "a+", to: "ab+" },
      { from: "a+", to: "ab-" },
      { from: "ab+", to: "abc+" },
      { from: "ab+", to: "abc-" },
      { from: "ab-", to: "ac+" },
      { from: "ab-", to: "ac-" },
      { from: "abc-", to: "abcd+" },
      { from: "abc-", to: "abcd-" },
      { from: "ac+", to: "acd+" },
      { from: "ac+", to: "acd-" },
      { from: "ac-", to: "ac-d+" },
      { from: "ac-", to: "ac-d-" },
      { from: "a-", to: "a-b+" },
      { from: "a-", to: "a-b-" },
    ]

    ops.tree(
      nodes,
      edges,
      "root",
      "Start with capacity 7 and the fractional-knapsack upper bound 116.",
    )
    ops.split(
      "root",
      ["root"],
      ["a+", "a-"],
      "Branch on A; depth-first search explores take A first.",
    )
    ops.incumbent(
      "a+",
      ["root", "a+"],
      40,
      "Take A: value 40 becomes the first feasible incumbent.",
    )
    ops.split("a+", ["root", "a+"], ["ab+", "ab-"], "Branch on B below take A.")
    ops.incumbent("ab+", ["root", "a+", "ab+"], 90, "Take B: A + B raises the incumbent to 90.")
    ops.split(
      "ab+",
      ["root", "a+", "ab+"],
      ["abc+", "abc-"],
      "Branch on C; the take branch is visited first.",
    )
    ops.reject("abc+", ["root", "a+", "ab+", "abc+"], "Take C exceeds capacity: weight 10 > 7.")
    ops.split(
      "abc-",
      ["root", "a+", "ab+", "abc-"],
      ["abcd+", "abcd-"],
      "Skip C and branch on D; the optimistic bound is 107.5.",
    )
    ops.reject(
      "abcd+",
      ["root", "a+", "ab+", "abc-", "abcd+"],
      "Take D exceeds capacity: weight 9 > 7.",
    )
    ops.prune(
      "abcd-",
      ["root", "a+", "ab+", "abc-", "abcd-"],
      [],
      "Skip D cannot beat incumbent 90: bound 90 ≤ 90.",
    )
    ops.split("ab-", ["root", "a+", "ab-"], ["ac+", "ac-"], "Backtrack, skip B, and branch on C.")
    ops.incumbent(
      "ac+",
      ["root", "a+", "ab-", "ac+"],
      105,
      "Take C: A + C exactly fills capacity and raises the incumbent to 105.",
    )
    ops.split(
      "ac+",
      ["root", "a+", "ab-", "ac+"],
      ["acd+", "acd-"],
      "Branch on D below the new incumbent.",
    )
    ops.reject(
      "acd+",
      ["root", "a+", "ab-", "ac+", "acd+"],
      "Take D exceeds capacity: weight 11 > 7.",
    )
    ops.prune(
      "acd-",
      ["root", "a+", "ab-", "ac+", "acd-"],
      [],
      "Skip D ties incumbent 105, so no better solution is possible.",
    )
    ops.prune(
      "ac-",
      ["root", "a+", "ab-", "ac-"],
      [],
      "Skip C loses on its bound: 75 ≤ incumbent 105; do not expand D.",
    )
    ops.prune(
      "a-",
      ["root", "a-"],
      [],
      "Skip A loses at the root: bound 102 ≤ incumbent 105; prune its whole subtree.",
    )
    ops.done("root", "best value 105", "Best feasible set is A + C with weight 7 and value 105.")
  },
} satisfies FamilyAlgorithmDefinition<
  "rectree",
  ExecutionTreeConfig,
  ExecutionTreeRecorder & ExecutionTreeOperations,
  ExecutionTreeFrame
>
