import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { gzipSync } from "node:zlib"
import { dirname, join, relative, sep } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import esbuild from "esbuild"
import { sassPlugin } from "esbuild-sass-plugin"

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, "..", "..", "..")
const src = join(here, "src")
const generated = join(here, "generated", "quartz")
const plugin = join(repo, "Vault", ".obsidian", "plugins", "flowmaid")
const manifestPath = join(here, "manifest.json")
const banner = "GENERATED by custom/flowmaid/build.mjs — do not edit. Edit src/ and rebuild."
const pathOf = (value) => relative(repo, value).split(sep).join("/")

const javascript = (entry, outfile, options = {}) => ({
  entryPoints: [join(src, entry)],
  bundle: true,
  outfile,
  platform: "browser",
  target: ["es2020"],
  charset: "utf8",
  legalComments: "none",
  metafile: true,
  banner: { js: `// ${banner}` },
  ...options,
})
const stylesheet = (entry, outfile) => ({
  entryPoints: [join(src, entry)],
  bundle: true,
  outfile,
  plugins: [sassPlugin()],
  charset: "utf8",
  legalComments: "none",
  minify: true,
  banner: { css: `/* ${banner} */` },
})
const obsidian = javascript("hosts/obsidian/main.cts", join(plugin, "main.js"), {
  format: "cjs",
  external: ["obsidian"],
})
const runtime = javascript("hosts/quartz/runtime.ts", join(generated, "flowmaid.js"), {
  format: "esm",
  minify: true,
})
const loader = javascript("hosts/quartz/loader.inline.ts", join(generated, "loader.js"), {
  format: "iife",
  write: false,
})
const component = javascript("hosts/quartz/component.tsx", join(generated, "component.js"), {
  format: "esm",
  external: ["./loader.inline"],
  write: false,
})

const output = (result, path) => {
  const file = result.outputFiles?.find((candidate) => candidate.path === path)
  if (!file) throw new Error(`flowmaid build: missing ${pathOf(path)}`)
  return file.text
}
const inputs = (result) => Object.keys(result.metafile?.inputs ?? {}).join("\n")
const reject = (name, result, pattern) => {
  const match = inputs(result).match(pattern)
  if (match) throw new Error(`flowmaid build: ${name} closure contains ${match[0]}`)
}
const allowInputs = (name, result, sources, dependencies = []) => {
  const sourceMarker = "custom/flowmaid/src/"
  const dependencyMarker = "node_modules/"
  const unexpected = Object.keys(result.metafile?.inputs ?? {})
    .map((input) => input.split(sep).join("/"))
    .find((input) => {
      const sourceAt = input.lastIndexOf(sourceMarker)
      if (sourceAt >= 0)
        return !sources.some((pattern) => pattern.test(input.slice(sourceAt + sourceMarker.length)))
      const dependencyAt = input.lastIndexOf(dependencyMarker)
      if (dependencyAt >= 0)
        return !dependencies.some((pattern) =>
          pattern.test(input.slice(dependencyAt + dependencyMarker.length)),
        )
      return true
    })
  if (unexpected) throw new Error(`flowmaid build: ${name} closure contains ${unexpected}`)
}

export const expectedArtifacts = async () => {
  const [obsidianBuild, runtimeBuild, loaderBuild, componentBuild, obsidianCss, quartzCss] =
    await Promise.all([
      esbuild.build({ ...obsidian, write: false }),
      esbuild.build({ ...runtime, write: false }),
      esbuild.build(loader),
      esbuild.build(component),
      esbuild.build({
        ...stylesheet("styles/obsidian.scss", join(plugin, "styles.css")),
        write: false,
      }),
      esbuild.build({
        ...stylesheet("styles/quartz.scss", join(generated, "flowmaid.css")),
        write: false,
      }),
    ])
  reject("Obsidian", obsidianBuild, /hosts\/quartz|@quartz-community|Web\/quartz/u)
  allowInputs(
    "Obsidian",
    obsidianBuild,
    [
      /^hosts\/obsidian\//u,
      /^authoring\//u,
      /^domain\//u,
      /^simulation\//u,
      /^mermaid\//u,
      /^runtime\//u,
      /^ui\//u,
      /^engine\.ts$/u,
    ],
    [/^yaml\//u],
  )
  reject(
    "Quartz runtime",
    runtimeBuild,
    /hosts\/obsidian|authoring\/|domain\/compile|yaml|obsidian|mdast|hast|unist/u,
  )
  allowInputs("Quartz runtime", runtimeBuild, [
    /^hosts\/quartz\/runtime\.ts$/u,
    /^domain\/types\.ts$/u,
    /^simulation\//u,
    /^mermaid\//u,
    /^runtime\//u,
    /^ui\//u,
    /^engine\.ts$/u,
  ])
  reject(
    "inline loader",
    loaderBuild,
    /src\/(?:engine|domain|simulation|mermaid|runtime|ui|styles)|generated/u,
  )
  allowInputs("inline loader", loaderBuild, [/^hosts\/quartz\/loader\.inline\.ts$/u])
  reject("Quartz component", componentBuild, /hosts\/quartz\/runtime|generated/u)
  allowInputs("Quartz component", componentBuild, [/^hosts\/quartz\/component\.tsx$/u])
  return {
    files: [
      { path: runtime.outfile, content: output(runtimeBuild, runtime.outfile) },
      {
        path: join(generated, "flowmaid.css"),
        content: output(quartzCss, join(generated, "flowmaid.css")),
      },
      { path: obsidian.outfile, content: output(obsidianBuild, obsidian.outfile) },
      {
        path: join(plugin, "styles.css"),
        content: output(obsidianCss, join(plugin, "styles.css")),
      },
      { path: join(plugin, "manifest.json"), content: readFileSync(manifestPath, "utf8") },
      { path: join(plugin, ".hotreload"), content: "" },
    ],
  }
}

const summary = (expected) => ({
  artifacts: expected.files.length,
  sizes: Object.fromEntries(
    expected.files
      .filter(({ path }) => path.endsWith(".js") || path.endsWith(".css"))
      .map(({ path, content }) => [
        pathOf(path),
        `${Buffer.byteLength(content)} B/${gzipSync(content).byteLength} B gzip`,
      ]),
  ),
})

const assertArtifactSet = () => {
  const directories = [
    [generated, ["flowmaid.css", "flowmaid.js"]],
    [plugin, [".hotreload", "main.js", "manifest.json", "styles.css"]],
  ]
  const unexpected = directories.flatMap(([directory, allowed]) =>
    readdirSync(directory)
      .filter((name) => !allowed.includes(name))
      .map((name) => pathOf(join(directory, name))),
  )
  if (unexpected.length)
    throw new Error(`flowmaid check: unexpected artifacts: ${unexpected.join(", ")}`)
}

export const buildFlowmaid = async () => {
  const expected = await expectedArtifacts()
  expected.files.forEach(({ path, content }) => {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
  })
  assertArtifactSet()
  return summary(expected)
}

export const verifyArtifacts = async () => {
  const expected = await expectedArtifacts()
  const stale = expected.files.filter(
    ({ path, content }) => !existsSync(path) || readFileSync(path, "utf8") !== content,
  )
  if (stale.length)
    throw new Error(
      `flowmaid check: stale artifacts: ${stale.map(({ path }) => pathOf(path)).join(", ")}`,
    )
  assertArtifactSet()
  return summary(expected)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const result = process.argv.includes("--check") ? await verifyArtifacts() : await buildFlowmaid()
  console.log(`flowmaid: ${result.artifacts} artifacts current; ${JSON.stringify(result.sizes)}`)
}
