import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, relative, sep } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import esbuild from "esbuild"
import { sassPlugin } from "esbuild-sass-plugin"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..", "..")
const srcDir = join(here, "src")
const generatedDir = join(here, "generated")
const manifestPath = join(here, "manifest.json")
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"))
const pluginDir = join(repoRoot, "Vault", ".obsidian", "plugins", manifest.id)

const generatedBanner =
  "GENERATED by custom/steptrace/build.mjs — do not edit. Edit src/ and rebuild."

const toRepoPath = (path) => relative(repoRoot, path).split(sep).join("/")

const browserOptions = {
  entryPoints: [join(srcDir, "entries", "browser.ts")],
  bundle: true,
  outfile: join(generatedDir, "engine.js"),
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  charset: "utf8",
  legalComments: "none",
  banner: { js: `// ${generatedBanner}` },
}

const obsidianOptions = {
  entryPoints: [join(srcDir, "entries", "obsidian.cts")],
  bundle: true,
  outfile: join(pluginDir, "main.js"),
  format: "cjs",
  platform: "node",
  target: ["node18"],
  external: ["obsidian"],
  charset: "utf8",
  legalComments: "none",
  banner: { js: `// ${generatedBanner}` },
}

const quartzStylesOptions = {
  entryPoints: [join(srcDir, "styles", "index.scss")],
  bundle: true,
  outfile: join(generatedDir, "engine.css"),
  plugins: [sassPlugin()],
  charset: "utf8",
  legalComments: "none",
  banner: { css: `/* ${generatedBanner} */` },
}

const obsidianStylesOptions = {
  entryPoints: [join(srcDir, "styles", "hosts", "obsidian.scss")],
  bundle: true,
  outfile: join(pluginDir, "styles.css"),
  plugins: [sassPlugin()],
  charset: "utf8",
  legalComments: "none",
  banner: { css: `/* ${generatedBanner} */` },
}

function outputContent(result, outputPath) {
  const output = result.outputFiles?.find((file) => file.path === outputPath)
  if (!output) throw new Error(`steptrace build: esbuild did not produce ${toRepoPath(outputPath)}`)
  return output.text
}

export async function expectedArtifacts() {
  const manifestSource = readFileSync(manifestPath, "utf8")
  const [browser, obsidian, quartzStyles, obsidianStyles] = await Promise.all([
    esbuild.build({ ...browserOptions, write: false }),
    esbuild.build({ ...obsidianOptions, write: false }),
    esbuild.build({ ...quartzStylesOptions, write: false }),
    esbuild.build({ ...obsidianStylesOptions, write: false }),
  ])

  return {
    manifestId: manifest.id,
    files: [
      {
        path: browserOptions.outfile,
        content: outputContent(browser, browserOptions.outfile),
      },
      {
        path: quartzStylesOptions.outfile,
        content: outputContent(quartzStyles, quartzStylesOptions.outfile),
      },
      {
        path: obsidianOptions.outfile,
        content: outputContent(obsidian, obsidianOptions.outfile),
      },
      {
        path: obsidianStylesOptions.outfile,
        content: outputContent(obsidianStyles, obsidianStylesOptions.outfile),
      },
      { path: join(pluginDir, "manifest.json"), content: manifestSource },
      { path: join(pluginDir, ".hotreload"), content: "" },
    ],
  }
}

export async function verifyArtifacts() {
  const expected = await expectedArtifacts()
  const stale = expected.files
    .filter(({ path, content }) => !existsSync(path) || readFileSync(path, "utf8") !== content)
    .map(({ path }) => toRepoPath(path))

  if (stale.length) {
    throw new Error(
      `steptrace check: generated artifacts are stale: ${stale.join(", ")}. Run npm run steptrace:build.`,
    )
  }
  return { manifestId: expected.manifestId, artifacts: expected.files.length }
}

export async function buildStepTrace({ mirrorPublic = false } = {}) {
  const expected = await expectedArtifacts()
  for (const { path, content } of expected.files) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
  }

  let quartzPublicSynced = false
  const publicRoot = join(repoRoot, "Web", "public")
  if (mirrorPublic && existsSync(publicRoot)) {
    for (const name of ["engine.js", "engine.css"]) {
      const source = join(generatedDir, name)
      const destination = join(publicRoot, "static", "steptrace", name)
      mkdirSync(dirname(destination), { recursive: true })
      writeFileSync(destination, readFileSync(source, "utf8"))
    }
    quartzPublicSynced = true
  }

  return {
    manifestId: expected.manifestId,
    artifacts: expected.files.length,
    quartzPublicSynced,
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv.includes("--check")) {
    const { manifestId, artifacts } = await verifyArtifacts()
    console.log(`steptrace: ${artifacts} generated artifacts are current (${manifestId})`)
  } else {
    const { manifestId, artifacts } = await buildStepTrace()
    console.log(`steptrace: built ${artifacts} artifacts for Quartz and Obsidian (${manifestId})`)
  }
}
