// steptrace build — assembles both host plugins from the single source engine.js.
// No compilation, just concat/copy; each host gets its OWN copy so the two plugins
// stay independent (neither reads the other's files at build or run time):
//   Obsidian → Vault/.obsidian/plugins/<id>/main.js   (engine.js + obsidian-plugin.js)
//   Quartz   → Web/quartz/static/steptrace/engine.js  (the component <script>-loads it)
// Run after editing engine.js or obsidian-plugin.js:  npm run steptrace:sync

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..", "..") // custom/steptrace → custom → Web → repo root

const engine = readFileSync(join(here, "engine.js"), "utf8")
const bootstrap = readFileSync(join(here, "obsidian-plugin.js"), "utf8")
const banner = "// GENERATED by custom/steptrace/sync.mjs — do not edit. Edit engine.js + obsidian-plugin.js.\n"

// 1) Obsidian plugin: engine + bootstrap concatenated into the vault plugin dir.
//    (The folder name must match the manifest id — Obsidian loads plugins by id.)
const manifest = JSON.parse(readFileSync(join(here, "manifest.json"), "utf8"))
const pluginDir = join(repoRoot, "Vault", ".obsidian", "plugins", manifest.id)
mkdirSync(pluginDir, { recursive: true })
writeFileSync(join(pluginDir, "main.js"), banner + engine + "\n" + bootstrap)
copyFileSync(join(here, "manifest.json"), join(pluginDir, "manifest.json"))

// 2) Quartz plugin: the engine's own served copy (the component loads it at runtime).
const staticDir = join(repoRoot, "Web", "quartz", "static", "steptrace")
mkdirSync(staticDir, { recursive: true })
writeFileSync(join(staticDir, "engine.js"), banner + engine)

console.log(
  `steptrace: engine.js → Vault/.obsidian/plugins/${manifest.id}/main.js (Obsidian) + Web/quartz/static/steptrace/engine.js (Quartz)`,
)
