// Builds the Obsidian plugin from the single engine.js + the plugin bootstrap.
//
// NO compilation: engine.js is a UMD file (runs verbatim everywhere), so the
// plugin's main.js is simply  engine.js  +  obsidian-plugin.js  concatenated —
// the engine sets globalThis.steptrace, the bootstrap below it uses it.
//
// Quartz needs NOTHING here: its component (custom/components/steptrace.tsx)
// reads engine.js and inlines it at build time, so a `quartz build` always
// picks up engine.js edits automatically.
//
// Run after editing engine.js or obsidian-plugin.js:  npm run steptrace:sync

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..", "..") // custom/steptrace → custom → Web → repo root

const engine = readFileSync(join(here, "engine.js"), "utf8")
const bootstrap = readFileSync(join(here, "obsidian-plugin.js"), "utf8")
const banner = "// GENERATED by custom/steptrace/sync.mjs — do not edit. Edit engine.js + obsidian-plugin.js.\n"

// The plugin folder must match the manifest id (Obsidian loads plugins by id).
const manifest = JSON.parse(readFileSync(join(here, "manifest.json"), "utf8"))
const pluginDir = join(repoRoot, "Vault", ".obsidian", "plugins", manifest.id)
mkdirSync(pluginDir, { recursive: true })
writeFileSync(join(pluginDir, "main.js"), banner + engine + "\n" + bootstrap)
copyFileSync(join(here, "manifest.json"), join(pluginDir, "manifest.json"))

console.log(`steptrace: engine.js + obsidian-plugin.js → Vault/.obsidian/plugins/${manifest.id}/main.js`)
