// steptrace build — stitches the src/ fragments into each host's single-file artifact.
// No compilation: the fragments are raw slices of ONE IIFE (shared scope), concatenated
// verbatim in the order listed below (ORDER), so the assembled engine is byte-for-byte
// what a single hand-authored file would be. Each host gets its OWN copy so the two
// plugins stay independent (neither reads the other's files at build or run time):
//   Obsidian → Vault/.obsidian/plugins/<id>/main.js   (engine + obsidian-plugin.js)
//   Quartz   → Web/quartz/static/steptrace/engine.js  (the component <script>-loads it)
// Run after editing anything under src/ or obsidian-plugin.js:  npm run steptrace:sync
// (or `npm run steptrace:watch` to re-run this automatically on every save).

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync } from "node:fs"
import { dirname, join, relative, sep } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..", "..") // custom/steptrace → custom → Web → repo root
const srcDir = join(here, "src")

const banner =
  "// GENERATED by custom/steptrace/sync.mjs — do not edit. Edit src/ + obsidian-plugin.js.\n"

// Concatenation order. These fragments are NOT modules — they are spliced verbatim
// into ONE shared-scope IIFE, so file order IS load order and it matters: `prologue`
// opens the wrapper; `registry`/`recorders` must precede the algorithm files that call
// registerX() at load time; the styles stack in cascade order; the algorithms are in
// teaching order (what listAlgorithms returns); `epilogue` closes the wrapper. Add a
// new fragment at its correct spot in this list — sync cross-checks the list against
// src/ and fails loudly if the two disagree, so nothing is silently dropped.
const ORDER = [
  "prologue.js",

  // §1 STYLES — one file per renderer kind, in cascade order.
  "styles/shared.js",
  "styles/bars.js",
  "styles/string.js",
  "styles/pointers.js",
  "styles/dp.js",
  "styles/unionfind.js",
  "styles/bits.js",
  "styles/backtrack.js",
  "styles/rectree.js",
  "styles/graph.js",
  "styles/status-toolbar.js",

  "registry.js", // §2 REGISTRY — defines registerX(), must precede the algorithms
  "recorders.js", // §3 RECORDERS

  // §4 ALGORITHMS — one file each, in teaching order (simple → advanced).
  "algorithms/bubble-sort.js",
  "algorithms/insertion-sort.js",
  "algorithms/selection-sort.js",
  "algorithms/quick-sort.js",
  "algorithms/heap-sort.js",
  "algorithms/merge-sort.js",
  "algorithms/bfs.js",
  "algorithms/dfs.js",
  "algorithms/dijkstra.js",
  "algorithms/prim.js",
  "algorithms/topological-sort.js",
  "algorithms/binary-search.js",
  "algorithms/linear-search.js",
  "algorithms/kmp.js",
  "algorithms/rabin-karp.js",
  "algorithms/two-pointers.js",
  "algorithms/sliding-window.js",
  "algorithms/lcs.js",
  "algorithms/union-find.js",
  "algorithms/kernighan-popcount.js",
  "algorithms/n-queens.js",
  "algorithms/fibonacci.js",

  "render.js", // §5 RENDER
  "player.js", // §6 PLAYER
  "mount.js", // §7 MOUNT
  "epilogue.js",
]

// ORDER resolved to absolute paths, cross-checked against what is actually on disk so
// a fragment can never be silently dropped (listed but missing) or silently ignored
// (present in src/ but absent from ORDER).
export function fragmentFiles() {
  const onDisk = new Set()
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name)
      if (entry.isDirectory()) walk(full)
      else if (entry.name.endsWith(".js")) onDisk.add(relative(srcDir, full).split(sep).join("/"))
    }
  }
  walk(srcDir)
  const listed = new Set(ORDER)
  const missing = ORDER.filter((p) => !onDisk.has(p))
  const unlisted = [...onDisk].filter((p) => !listed.has(p))
  if (missing.length) {
    throw new Error(`steptrace sync: ORDER lists files not in src/: ${missing.join(", ")}`)
  }
  if (unlisted.length) {
    throw new Error(
      `steptrace sync: src/ files missing from ORDER in sync.mjs: ${unlisted.join(", ")}`,
    )
  }
  return ORDER.map((p) => join(srcDir, p))
}

// Concatenate the fragments verbatim into the assembled engine source.
export function buildEngine() {
  return fragmentFiles()
    .map((f) => readFileSync(f, "utf8"))
    .join("")
}

// Assemble both host artifacts from src/. Importable so watch.mjs can call it.
export function stitch() {
  const engine = buildEngine()
  const bootstrap = readFileSync(join(here, "obsidian-plugin.js"), "utf8")

  // 1) Obsidian plugin: engine + bootstrap concatenated into the vault plugin dir.
  //    (The folder name must match the manifest id — Obsidian loads plugins by id.)
  const manifest = JSON.parse(readFileSync(join(here, "manifest.json"), "utf8"))
  const pluginDir = join(repoRoot, "Vault", ".obsidian", "plugins", manifest.id)
  mkdirSync(pluginDir, { recursive: true })
  writeFileSync(join(pluginDir, "main.js"), banner + engine + "\n" + bootstrap)
  copyFileSync(join(here, "manifest.json"), join(pluginDir, "manifest.json"))
  // The Hot Reload community plugin watches for this marker; keep it present so a
  // freshly-synced main.js reloads without toggling the plugin by hand.
  writeFileSync(join(pluginDir, ".hotreload"), "")

  // 2) Quartz plugin: the engine's own served copy (the component loads it at runtime).
  const staticDir = join(repoRoot, "Web", "quartz", "static", "steptrace")
  mkdirSync(staticDir, { recursive: true })
  writeFileSync(join(staticDir, "engine.js"), banner + engine)

  return { manifestId: manifest.id, fragments: fragmentFiles().length }
}

// Run the stitch when invoked directly (npm run steptrace:sync); stay importable
// (no side effects) when watch.mjs pulls in stitch().
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { manifestId, fragments } = stitch()
  console.log(
    `steptrace: ${fragments} src/ fragments → Vault/.obsidian/plugins/${manifestId}/main.js (Obsidian) + Web/quartz/static/steptrace/engine.js (Quartz)`,
  )
}
