import type { WatchRow } from "./types"

export const WATCH_HINTS = Object.freeze({
  i: "First active array index.",
  j: "Second active array index.",
  at: "Array index currently being inspected.",
  from: "Index a value moves from.",
  pivot: "Pivot index and value for this partition.",
  range: "Active search or sort index range.",
  swaps: "Swaps completed so far.",
  moves: "Value moves completed so far.",
  held: "Value temporarily held outside the array.",
  home: "Index where the current value belongs.",
  gap: "Distance between compared array positions.",
  lane: "Indices in the active gapped subsequence.",
  target: "Value the algorithm is looking for.",
  goal: "Result the algorithm is trying to optimize.",
  phase: "Current stage of the algorithm.",
  subproblem: "Active part of the problem being solved recursively.",
  "call path": "Active calls from the root down to the current subproblem.",
  result: "Answer returned by the active subproblem.",
  probe: "Index and value currently being checked.",
  "probe 1": "First third-point checked in the current range.",
  "probe 2": "Second third-point checked in the current range.",
  estimate: "Index predicted from the target's position in the value range.",
  block: "Number of array positions in each jump.",
  "days used": "Shipping days needed at the tested capacity.",
  capacity: "Candidate ship capacity currently being tested.",
  verdict: "Whether the candidate satisfies the feasibility check.",
  scanned: "Array positions inspected so far.",
  mid: "Middle index and value of the current range.",
  shift: "Pattern offset under the text.",
  matches: "Matches found so far.",
  hash: "Current window hash and pattern hash.",
  align: "Pattern offset under the text.",
  suffix: "Pattern suffix already matched right-to-left.",
  "bad shift": "Shift proposed by the bad-character rule.",
  "good shift": "Shift proposed by the good-suffix rule.",
  "selected shift": "Larger proposed shift and the rule that selected it.",
  "z-box": "Inclusive range whose text is already known to match the prefix.",
  source: "How Z[i] was obtained: direct comparison, mirrored copy, or edge extension.",
  "z[i]": "Prefix-match length recorded at the active suffix index.",
  l: "Left pointer index and value.",
  left: "Left pointer index and value.",
  lo: "Left boundary index and value.",
  r: "Right pointer index and value.",
  right: "Right pointer index and value.",
  hi: "Right boundary index and value.",
  cell: "Dynamic-programming cell being computed.",
  value: "Value computed for the current cell.",
  "stage k": "Intermediate vertex currently allowed in shortest paths.",
  "dist[i][j]": "Distance entry currently being relaxed.",
  "dist[i][k]": "Distance from the source to the permitted intermediate vertex.",
  "dist[k][j]": "Distance from the permitted intermediate vertex to the destination.",
  candidate: "Distance produced by routing through the permitted intermediate vertex.",
  decision: "Whether the candidate improves the current distance or the current value is kept.",
  "negative cycle": "Vertices whose diagonal distance became negative.",
  sets: "Disjoint sets currently remaining.",
  edge: "Edge currently being examined.",
  x: "Current integer and its binary representation.",
  "lowest 1": "Position of the lowest set bit.",
  "1s cleared": "Set bits removed so far.",
  depth: "Current recursion depth.",
  trying: "Candidate position currently being tried.",
  pruned: "Candidate branches rejected so far.",
  calls: "Function calls made so far.",
  memo: "Most recent cached result.",
  event: "Current recursion or memoization event.",
  queue: "Nodes waiting to be processed.",
  visited: "Nodes already processed.",
  current: "Node the graph algorithm is processing now.",
  score: "Exact cost g, remaining estimate h, and their priority f.",
  expanded: "Nodes expanded by A* compared with Dijkstra.",
  comparison: "Final Greedy path cost compared with the optimal A* path cost.",
  frontiers: "Nodes waiting on the forward and backward search sides.",
  meeting: "First node reached from both search directions.",
  pass: "Current full scan through the graph's edges.",
  change: "Whether the active operation changed the stored state.",
  component: "Connected component currently being discovered or merged.",
  frontier: "Nodes discovered but not processed yet.",
  "disc / low": "Discovery order and earliest reachable ancestor for the active node.",
  "cut vertices": "Vertices currently proven to disconnect the graph if removed.",
  bridges: "Edges currently proven to disconnect the graph if removed.",
  stack: "Active DFS nodes not yet assigned to a completed component.",
  components: "Components currently formed or completed.",
  pending: "Edges not processed yet.",
  accepted: "Edges already accepted into the result.",
  weight: "Total weight of accepted tree edges.",
  round: "Current component-selection round.",
  path: "Current path selected by the algorithm.",
  candidates: "Next nodes that can extend the active path.",
  rejected: "Choices rejected by the current branch or graph constraint.",
  bottleneck: "Smallest residual capacity on the augmenting path.",
  flow: "Total flow currently reaching the sink.",
  strategy: "Sorting strategy active on the current range.",
  cutoff: "Largest range deferred to insertion sort.",
  operation: "Trie operation and key currently being processed.",
  character: "Character on the active trie edge.",
  test: "Whether the current path or terminal-marker test succeeded.",
  state: "Active automaton or character-tree state.",
  output: "Patterns emitted at the current text position.",
  "next interval": "Sorted interval currently compared with the accumulated block.",
  "current block": "Merged interval accumulated by the left-to-right sweep.",
  "next meeting": "Finish-time-ordered meeting currently being checked.",
  "last accepted": "Most recent meeting committed to the schedule.",
  slow: "The pointer that advances one node at a time.",
  fast: "The pointer that advances two nodes at a time during cycle detection.",
  head: "The pointer reset to the head for the cycle-entry search.",
})

export function watchHintFor(row: WatchRow): string {
  const override = row.hint?.trim()
  if (override) return override
  const label = row.k.trim().toLowerCase()
  return WATCH_HINTS[label] || `Current ${row.k.trim()} value.`
}
