#!/usr/bin/env python3
"""Regenerate Vault/Home/Changelog.md from GitHub release descriptions.

Usage:
    python3 .scripts/generate-changelog.py

Fetches every release for the repo via `gh api --paginate`, splits each
release body into an AI-written summary (the lines between
`<!--ai-summary:start-->`/`<!--ai-summary:end-->`, when a manual
summarization routine has added them) and the git-cliff detail section, and
overwrites Vault/Home/Changelog.md wholesale. The file is 100% generated —
there is no marker/partial-replace logic, run it again to refresh.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHANGELOG_PATH = os.path.join(REPO_ROOT, "Vault", "Home", "Changelog.md")
REPO_SLUG = "grafanaKibana/devbook.zip"

SUMMARY_START = "<!--ai-summary:start-->"
SUMMARY_END = "<!--ai-summary:end-->"
VERSION_HEADER_RE = re.compile(r"^## v")

FRONTMATTER = """---
title: Changelog
publish: true
tags:
  - MetricsIgnore
icon: history
---

<!-- Generated by .scripts/generate-changelog.py — do not hand-edit. -->
"""


@dataclass
class Release:
    tag: str
    date: str
    body: str


def fetch_releases(repo: str = REPO_SLUG) -> list[Release]:
    result = subprocess.run(
        ["gh", "api", "--paginate", f"repos/{repo}/releases"],
        check=True,
        text=True,
        capture_output=True,
    )
    raw = json.loads(result.stdout)
    releases = [
        Release(
            tag=item.get("tag_name") or "",
            date=(item.get("published_at") or "")[:10],
            body=item.get("body") or "",
        )
        for item in raw
    ]
    releases.sort(key=lambda r: r.date, reverse=True)
    return releases


def split_body(body: str) -> tuple[list[str], str]:
    """Split a release body into (summary bullet lines, detail text).

    If the body has an `ai-summary` block, its non-blank lines become
    `summary` and everything after the end marker becomes `detail`.
    Otherwise `summary` is empty and `detail` is the whole body. Either way,
    a leading git-cliff `## v...` header line is stripped from `detail`
    since the version/date are rendered from the release fields instead.
    """
    start = body.find(SUMMARY_START)
    end = body.find(SUMMARY_END)
    if start != -1 and end != -1 and end > start:
        summary_block = body[start + len(SUMMARY_START) : end]
        summary = [line.strip() for line in summary_block.splitlines() if line.strip()]
        detail = body[end + len(SUMMARY_END) :]
    else:
        summary = []
        detail = body

    # A prepended summary block leaves a blank line (its own trailing
    # newline) before the git-cliff header, so drop blank edges first —
    # otherwise the header never lands on line 0 and never gets stripped.
    detail_lines = detail.strip("\n").splitlines()
    if detail_lines and VERSION_HEADER_RE.match(detail_lines[0]):
        detail_lines = detail_lines[1:]
    detail = "\n".join(detail_lines).strip()

    return summary, detail


def render_entry(release: Release) -> str:
    summary, detail = split_body(release.body)

    lines = [f"### {release.tag} ({release.date})"]
    lines.extend(summary)
    if detail:
        lines.append("> [!note]- Details")
        # Every line, including blank ones, must carry the "> " quote marker
        # or the callout closes early and later sections spill outside it.
        lines.extend((f"> {line}" if line else ">") for line in detail.splitlines())

    return "\n".join(lines)


def render_changelog(releases: list[Release]) -> str:
    body = "\n\n".join(render_entry(release) for release in releases)
    return FRONTMATTER + "\n" + body + "\n"


def main() -> int:
    releases = fetch_releases()
    content = render_changelog(releases)
    with open(CHANGELOG_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Changelog.md: {len(releases)} releases written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
